import assert from 'node:assert/strict';
import { mkdtemp, readFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { arenaConfigSchema, arenaObservationSchema, evaluateArena, loadArenaConfig, writeArenaReport } from '../src/model-arena.js';
import { assertBaselineEligible, cohortConfigSchema, cohortManifest, generateCohort, loadCohortConfig, selectCohortPersonas, toStudentPersona } from '../src/synthetic-cohorts.js';

const measured=(value:number|null,measurement:'observed'|'estimated'|'unknown')=>({value,measurement});
test('arena config/version/self-judge contracts fail closed',async()=>{const config=await loadArenaConfig('config/arena-fixture.yaml');assert.equal(config.schemaVersion,1);assert.throws(()=>arenaConfigSchema.parse({...config,schemaVersion:2}));assert.throws(()=>arenaConfigSchema.parse({...config,configurations:[config.configurations[0],{...config.configurations[1],brain:config.configurations[1]!.evaluator}]}));assert.throws(()=>arenaObservationSchema.parse({configurationId:'x',repeat:0,seed:1,qualityScore:1,hardBlockers:0,reliability:1,latencyMs:measured(null,'observed'),cost:measured(null,'unknown'),evidenceVersion:'1'}));});
test('arena comparability, blocker exclusion, deterministic rank/tie, variance and unknown cost',async()=>{const config=await loadArenaConfig('config/arena-fixture.yaml');const observations=config.configurations.flatMap((c,ci)=>[0,1,2].map((repeat)=>({configurationId:c.id,repeat,seed:config.seed,qualityScore:ci?90:80,hardBlockers:ci?0:repeat===0?1:0,reliability:.99,latencyMs:measured(ci?120:100,'observed' as const),cost:measured(null,'unknown' as const),evidenceVersion:'eval-v1'})));const report=evaluateArena(config,observations);assert.equal(report.comparable,true);assert.equal(report.entries.find(x=>x.configurationId==='scripted-baseline')?.rank,null);assert.equal(report.entries.find(x=>x.configurationId==='scripted-adaptive')?.rank,1);assert.equal(report.entries[0]?.cost.measurement,'unknown');assert.equal(report.entries[1]?.consistencyVariance,0);const tie=evaluateArena(config,observations.map(x=>({...x,hardBlockers:0,qualityScore:90})));assert.deepEqual(tie.entries.map(x=>x.rank),[1,1]);assert.equal(evaluateArena(config,observations.map((x,i)=>i===0?{...x,evidenceVersion:'other'}:x)).comparable,false);});
test('arena report artifacts are written',async()=>{const config=await loadArenaConfig('config/arena-fixture.yaml');const observations=config.configurations.flatMap(c=>[0,1,2].map(repeat=>({configurationId:c.id,repeat,seed:config.seed,qualityScore:80,hardBlockers:0,reliability:1,latencyMs:measured(null,'unknown' as const),cost:measured(null,'unknown' as const),evidenceVersion:'v1'})));const root=await mkdtemp(path.join(os.tmpdir(),'arena-'));await writeArenaReport(root,evaluateArena(config,observations));assert.match(await readFile(path.join(root,'arena.json'),'utf8'),/configurationHash/);assert.match(await readFile(path.join(root,'report.md'),'utf8'),/not a marketing benchmark/);});
test('cohorts are versioned, bounded, PII-free and deterministic',async()=>{const golden=await loadCohortConfig('config/cohort-golden.yaml');const exploratory=await loadCohortConfig('config/cohort-exploratory.yaml');assert.equal(generateCohort(golden).length,3);const a=cohortManifest(exploratory),b=cohortManifest(exploratory),c=cohortManifest({...exploratory,seed:exploratory.seed+1});assert.deepEqual(a,b);assert.notDeepEqual(a.personas.map(x=>x.dimensions),c.personas.map(x=>x.dimensions));assert.equal(a.personaCount,6);assert.equal(JSON.stringify(a).match(/name|email|phone|address/gi),null);assertBaselineEligible(a);assert.equal(selectCohortPersonas(a,2).length,2);assert.equal(toStudentPersona(a.personas[0]!).version,1);assert.throws(()=>cohortConfigSchema.parse({...exploratory,schemaVersion:2}));assert.throws(()=>cohortConfigSchema.parse({...exploratory,maxPersonas:51}));});
