import assert from 'node:assert/strict';
import test from 'node:test';
import { optimizerCandidateSchema, optimizeCandidates, type OptimizerConfig } from '../src/quality-optimizer.js';
import { evaluateSafetySuite, redactSafetyEvidence, safetyScenarioSchema, validateSafetyAction } from '../src/safety-lab.js';

const scenario = safetyScenarioSchema.parse({ schemaVersion: 1, id: 'fixture', name: 'fixture', category: 'tool_safety', severity: 'CRITICAL', input: { source: 'scripted_agent_action', content: 'synthetic safe wording', synthetic: true }, expected: { decision: 'DENY', reasonCode: 'tool-denied', blocker: true }, evidenceLabels: ['fixture'] });
test('safety schema fails closed and controller denies injection/tool actions', () => { assert.throws(() => safetyScenarioSchema.parse({ ...scenario, schemaVersion: 2 })); for (const action of ['shell', 'cloud_console', 'payment', 'navigate']) assert.equal(validateSafetyAction({ action, target: 'https://unknown.test' }).allowed, false); });
test('safety evaluator gives blocker precedence', () => { const report = evaluateSafetySuite([scenario], { fixture: { action: 'allow_safe_response', text: 'unsafe allowance' } }); assert.equal(report.status, 'FAIL'); assert.equal(report.blockers, 1); });
test('safety evidence redacts PII and secrets', () => { const value = JSON.stringify(redactSafetyEvidence({ text: '0901234567 child@example.test', token: 'secret' })); assert.doesNotMatch(value, /0901234567|child@example\.test|secret/); });

const config: OptimizerConfig = { schemaVersion: 1, id: 'fixture', constraints: { qualityScoreMinimum: 85, p95LatencyMsMaximum: 2500, costPerSessionMaximum: .5, criticalFailuresMaximum: 0 }, costFormula: { version: 1, currency: 'USD', sessionMinutes: 30, assumptions: ['fixture'] }, routingProposals: [{ route: 'simple_turn', candidateId: 'a', rationale: 'fixture', limitation: 'fixture only' }] };
const metric = (value: number | null, measurement: 'observed' | 'estimated' | 'unknown') => ({ value, measurement }); const costs = { inputUnits: 1, outputUnits: 1, audioMinutes: 0, inputRate: .1, outputRate: .1, audioMinuteRate: .1 };
const candidate = (id: string, quality = 90, latency = 1000, cost = .2, criticalFailures = 0) => optimizerCandidateSchema.parse({ id, qualityScore: metric(quality, 'observed'), p95LatencyMs: metric(latency, 'observed'), costPerSession: metric(cost, 'observed'), criticalFailures, evidence: ['fixture'], costInputs: costs });
test('optimizer enforces constraints, critical failure and unknown provenance', () => { const unknown = { ...candidate('unknown'), p95LatencyMs: metric(null, 'unknown') }; const report = optimizeCandidates(config, [candidate('a'), candidate('bad-quality', 80), candidate('critical', 99, 500, .01, 1), optimizerCandidateSchema.parse(unknown)]); assert.deepEqual(report.entries.map((x) => x.status), ['ELIGIBLE', 'REJECTED', 'REJECTED', 'NEEDS_REVIEW']); assert.equal(report.providerConfigMutated, false); assert.equal(report.deployed, false); });
test('optimizer computes Pareto and deterministic stable-id ties', () => { const report = optimizeCandidates(config, [candidate('b'), candidate('a'), candidate('dominated', 86, 2000, .4)]); assert.deepEqual(report.paretoFrontier, ['a', 'b']); assert.equal(report.entries.find((x) => x.candidateId === 'a')?.rank, 1); assert.equal(report.entries.find((x) => x.candidateId === 'b')?.rank, 1); });
test('unknown cost inputs remain unknown, never zero', () => { const raw = candidate('a'); const unknown = optimizerCandidateSchema.parse({ ...raw, costPerSession: metric(null, 'unknown'), costInputs: { ...costs, inputRate: null } }); const entry = optimizeCandidates(config, [unknown]).entries[0]!; assert.equal(entry.status, 'NEEDS_REVIEW'); assert.equal(entry.costPerSession.value, null); assert.equal(entry.costPerSession.measurement, 'unknown'); });
