import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { parse as parseYaml } from 'yaml';
import { z } from 'zod';
import type { StudentPersona } from './student-contracts.js';

export const COHORT_SCHEMA_VERSION = 1 as const;
const id = z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/);
const dimensionsSchema = z.object({
  ability: z.enum(['foundation-lost', 'average', 'strong', 'fast-careless']),
  misconception: z.enum(['numerator-denominator', 'pattern-guessing', 'rule-without-understanding']),
  behavior: z.enum(['silent', 'off-topic', 'discouraged', 'answers-too-fast']),
  communication: z.enum(['fragmented', 'hesitant', 'limited-vocabulary', 'age-appropriate']),
  environment: z.enum(['quiet', 'poor-mic', 'background-noise', 'unstable-network']),
  learningPsychology: z.enum(['low-confidence', 'praise-responsive', 'distracted']),
}).strict();
export const cohortPersonaSchema = z.object({ schemaVersion: z.literal(COHORT_SCHEMA_VERSION), id, grade: z.number().int().min(1).max(12), locale: z.literal('vi-VN'), synthetic: z.literal(true), dimensions: dimensionsSchema }).strict();
export const cohortConfigSchema = z.object({ schemaVersion: z.literal(COHORT_SCHEMA_VERSION), id, kind: z.enum(['golden', 'exploratory']), seed: z.number().int().nonnegative(), maxPersonas: z.number().int().min(2).max(50), personas: z.array(cohortPersonaSchema).max(50).optional() }).strict().superRefine((value, context) => { if (value.kind === 'golden' && (!value.personas || value.personas.length < 2)) context.addIssue({ code: 'custom', message: 'Golden cohort requires fixed personas.', path: ['personas'] }); if (value.kind === 'exploratory' && value.personas) context.addIssue({ code: 'custom', message: 'Exploratory cohort must be generated from seed.', path: ['personas'] }); });
export type CohortConfig = z.infer<typeof cohortConfigSchema>;
export type CohortPersona = z.infer<typeof cohortPersonaSchema>;
const pools = { ability: ['foundation-lost', 'average', 'strong', 'fast-careless'], misconception: ['numerator-denominator', 'pattern-guessing', 'rule-without-understanding'], behavior: ['silent', 'off-topic', 'discouraged', 'answers-too-fast'], communication: ['fragmented', 'hesitant', 'limited-vocabulary', 'age-appropriate'], environment: ['quiet', 'poor-mic', 'background-noise', 'unstable-network'], learningPsychology: ['low-confidence', 'praise-responsive', 'distracted'] } as const;
function rng(seed: number): () => number { let state = seed >>> 0; return () => { state = (state * 1664525 + 1013904223) >>> 0; return state / 0x1_0000_0000; }; }
const pick = <T>(items: readonly T[], random: () => number): T => items[Math.floor(random() * items.length)]!;
export async function loadCohortConfig(filePath: string): Promise<CohortConfig> { return cohortConfigSchema.parse(parseYaml(await readFile(filePath, 'utf8')) as unknown); }
export function generateCohort(configRaw: CohortConfig): readonly CohortPersona[] { const config = cohortConfigSchema.parse(configRaw); if (config.kind === 'golden') return config.personas!; const random = rng(config.seed); const output: CohortPersona[] = []; const signatures = new Set<string>(); let attempts = 0; while (output.length < config.maxPersonas && attempts++ < config.maxPersonas * 20) { const dimensions = { ability: pick(pools.ability, random), misconception: pick(pools.misconception, random), behavior: pick(pools.behavior, random), communication: pick(pools.communication, random), environment: pick(pools.environment, random), learningPsychology: pick(pools.learningPsychology, random) }; const signature = JSON.stringify(dimensions); if (signatures.has(signature)) continue; signatures.add(signature); output.push(cohortPersonaSchema.parse({ schemaVersion: 1, id: `${config.id}-${String(output.length + 1).padStart(2, '0')}`, grade: 4, locale: 'vi-VN', synthetic: true, dimensions })); } if (output.length !== config.maxPersonas) throw new Error('Unable to generate bounded unique cohort.'); return output; }
export function cohortManifest(configRaw: CohortConfig) { const config = cohortConfigSchema.parse(configRaw); const personas = generateCohort(config); return { schemaVersion: COHORT_SCHEMA_VERSION, cohortId: config.id, kind: config.kind, seed: config.seed, configurationHash: createHash('sha256').update(JSON.stringify(config)).digest('hex'), personaCount: personas.length, piiFree: true, personas }; }
export function assertBaselineEligible(manifest: ReturnType<typeof cohortManifest>): void { if (manifest.kind === 'exploratory' && (!Number.isInteger(manifest.seed) || !manifest.configurationHash)) throw new Error('Exploratory cohort requires recorded seed and configuration hash for baseline comparison.'); }
export function selectCohortPersonas(manifest: ReturnType<typeof cohortManifest>, limit: number): readonly CohortPersona[] { if (!Number.isInteger(limit) || limit < 1 || limit > manifest.personaCount) throw new Error('Invalid cohort selection limit.'); return manifest.personas.slice(0, limit); }
export function toStudentPersona(persona: CohortPersona): StudentPersona { const behaviorMap = { silent: 'silence_once', 'off-topic': 'off_topic_once', discouraged: 'ask_for_example_once', 'answers-too-fast': 'repeat_mistake_once' } as const; return { version: 1, id: persona.id, name: `Học sinh tổng hợp ${persona.id}`, grade: persona.grade, locale: 'vi-VN', starting_understanding: persona.dimensions.ability === 'foundation-lost' ? 1 : persona.dimensions.ability === 'average' ? 2 : 3, misconception: persona.dimensions.misconception, communication: { confidence: persona.dimensions.learningPsychology === 'low-confidence' ? 'low' : 'medium', vocabulary: persona.dimensions.communication === 'limited-vocabulary' ? 'limited' : 'age-appropriate', response_style: persona.dimensions.communication === 'hesitant' ? 'hesitant' : persona.dimensions.communication === 'age-appropriate' ? 'detailed' : 'short' }, behaviors: [behaviorMap[persona.dimensions.behavior]] }; }
